-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Visitor CASCADE;
DROP TABLE IF EXISTS Chore CASCADE;
DROP TABLE IF EXISTS Category CASCADE;
DROP TABLE IF EXISTS Checklist CASCADE;
DROP TABLE IF EXISTS ChoreChecklist CASCADE;
DROP TABLE IF EXISTS ChoreCategory CASCADE;
