-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Visitor CASCADE;
DROP TABLE IF EXISTS Chore CASCADE;
DROP TABLE IF EXISTS Category CASCADE;
DROP TABLE IF EXISTS ChoreCategory CASCADE;
DROP TABLE IF EXISTS Kayttaja CASCADE;
DROP TABLE IF EXISTS Askare CASCADE;
DROP TABLE IF EXISTS Luokka CASCADE;
DROP TABLE IF EXISTS Muistilista CASCADE;
DROP TABLE IF EXISTS AskareMuistilista CASCADE;
DROP TABLE IF EXISTS AskareLuokka CASCADE;